### ISSUE TITLE
How to install burpa in Windows machine

### ISSUE THREAD

**Issue by ganesh2183** [tristanlatr/burpa#15]
Hi,

How to install burpa in Windows OS machine.

Python & Pip version supported ?

**Comment by tristanlatr** [comment]
No idea! Just try it out the usual way and see if it works :)

**Comment by ganesh2183** [comment]
Hi @tristanlatr 

When i try to run 'burpa' command, getting the error (attached screenshot for reference).

![16642926838962073618604903271188](https://user-images.githubusercontent.com/41476297/192570025-36e8ac77-5ffe-4ad4-99da-91162af7bee4.jpg)

**Comment by ganesh2183** [comment]
@tristanlatr  Please help on this issue to resolve it.

**Comment by tristanlatr** [comment]
This looks like an issue with python-dotenv. 

The root cause is probably linked to the fact that your burpa installation resides in another drive than your current working directory.

You could open a pull request and  introduce a new option: `--no-dotenv`, which would skip the `find_dotenv()` call in `Burpa.__init__`, this will solve your issue. But as a side effect, you won’t be able to use `.env` files to store burpa configurations.

Tell me what you think,

**Comment by ganesh2183** [comment]
@tristanlatr i tried installing burpa installation in same current working directory (C:\Program Files). Burpsuite and Python3.9 installed in 'C:\Program Files'

where & how to use --no-dotenv option.

Python version recommended? Any other way to resolve this issue.

**Comment by tristanlatr** [comment]
--no-dotenv option Does not exist yet. What I’m saying is that you could create that option to work around your problem. Tell me if you think that’s possible.

**Comment by ganesh2183** [comment]
@tristanlatr I think somehow i have fixed error related with python-dotenv. I tried to install the burpa package by running '**pip install burp.**' command from burpa directory. But now i'm getting different error message as "**FileNotFound: [WinError 3] The system cannot find the path specified: '\\tmp\\burp-temp'** ". Attached the screenshot for the reference.

Could you please let me know how to fix this error.
![WhatsApp Image 2022-10-03 at 9 54 24 PM](https://user-images.githubusercontent.com/41476297/193629423-6f76ffcb-82e0-4e16-b26d-bd7ebb3e78aa.jpeg)

**Comment by tristanlatr** [comment]
Please try installing burpa with `pip install git+https://github.com/tristanlatr/burpa`, it should install the latest version.

**Comment by ganesh2183** [comment]
@tristanlatr It worked. Thanks :-)
