### ISSUE TITLE
Burp Suite v2023.7.2 breaks Burpa

### ISSUE THREAD

**Issue by mariobrostech** [tristanlatr/burpa#24]
Hi,

After updating my Burp Suite JAR file to v2023.7.2, I noticed that none of my scans were returning any reports following the update. I did some testing, and it looks like something has changed in the latest Burp Suite release that breaks Burpa. Every scan that I perform shows the proper logging in the Burp Suite interface itself (with headless mode disabled), but none of these errors reach the Burpa console log.

As a result, each scan ends with the message "No issue could be found for the target http://..." and doesn't output anything to the folder that I have specified the reports to be saved to. I can't tell if this is an issue with Burpa or one of the other APIs that it's using to generate reports. If you could please look into this, I would really appreciate it! Additionally, if you need help reproducing the issue, I'd be happy to assist.

Thanks in advance for your help!

**Comment by tristanlatr** [comment]
You're right, I'm having the same issue. I think the issue should be reported in [but-rest-api](https://github.com/vmware/burp-rest-api) repo, it's not related to our processes in burpa. 

Thanks fort he report.

**Comment by tristanlatr** [comment]
Im open for suggestions, @mariobrostech... Have you tried with newer version of Burp Suite ?

**Comment by tristanlatr** [comment]
I don't see anything in the release notes that could point into dropping support for whatever we're doing here.

**Comment by tristanlatr** [comment]
Just tested with Burp 2023.10.1.1 and it worked. Tell me if this works on your side as well @mariobrostech
